# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run test
    - run: git clone --depth 1 https://github.com/APIs-guru/openapi-directory.git
    - run: git clone --depth 1 https://github.com/mermade/openapi-definitions.git
    - run: git clone --depth 1 https://github.com/mermade/openapi3-examples.git
    - run: . ./bin/setflags.sh
    - run: mkdir -p out
    - run: node widdershins -o out/petstore.md defs/petstore3.json
    - run: node node_modules/mdv/mdv out/petstore.md
    - run: node $nflags testRunner openapi-directory/APIs/
    - run: node $nflags testRunner openapi-definitions/
    - run: node $nflags testRunner openapi3-examples/3.0/pass/
    - run: node $nflags testRunner --resolve defs/
